---
title: "How Does Velocity Affect Fastball Success?"
author: "Luke Stageberg"
date: "March 25, 2019"
output: html_document
---

```{r}
fb_velo = read.csv('../data/Fastball_Data.csv')
#Naming the dataset "fb_velo" and importing it from my data folder in my Fastball_Velocity folder
```

```{r}
hist(fb_velo$velocity, breaks = 20)
#Creating a histogram to show the viewer what the average fastball velocity's were across the MLB in 2018
```

```{r}
mod_velo_ba = lm(formula = ba ~ velocity, data = fb_velo)
#Creating a model using velocity as a predictor varibale for batting average
```

```{r}
summary(mod_velo_ba)
#Producing a summary of the model from above (velocity predicting batting average)
```

```{r}
scatter.smooth(x=fb_velo$velocity, y=fb_velo$ba, main="ba ~ velocity")
#Creating a scatter plot with a line of best fit as a visual alongside the model (showing the relationship between batting average and average fastball velocity)
```

```{r}
mod_velo_slg = lm(formula = slg ~ velocity, data = fb_velo)
#Creating a model using velocity as a predictor varibale for slugging percentage
```

```{r}
summary(mod_velo_slg)
#Producing a summary of the model from above (velocity predicting slugging percentage)
```

```{r}
scatter.smooth(x=fb_velo$velocity, y=fb_velo$slg, main="slg ~ velocity")
#Creating a scatter plot with a line of best fit as a visual alongside the model (showing the relationship between slugging percentage and average fastball velocity)
```

```{r}
mod_spin_ba = lm(formula = ba ~ spin_rate, data = fb_velo)
#Creating a model using spin rate as a predictor varibale for batting average
```

```{r}
summary(mod_spin_ba)
#Producing a summary of the model from above (spin rate predicting batting average)
```

```{r}
scatter.smooth(x=fb_velo$spin_rate, y=fb_velo$ba, main="ba ~ spin_rate")
#Creating a scatter plot with a line of best fit as a visual alongside the model (showing the relationship between batting average and average fastball spin rate)
```

```{r}
mod_spin_slg = lm(formula = slg ~ spin_rate, data = fb_velo)
#Creating a model using spin rate as a predictor varibale for sluggling percentage
```

```{r}
summary(mod_spin_slg)
#Producing a summary of the model from above (spin rate predicting sluggling percentage)
```

```{r}
scatter.smooth(x=fb_velo$spin_rate, y=fb_velo$slg, main="slg ~ spin_rate")
#Creating a scatter plot with a line of best fit as a visual alongside the model (showing the relationship between slugging percentage and average fastball spin rate)
```

```{r}
fb_velo$swing_and_miss_pct = with(fb_velo, whiffs / swings)
fb_velo[is.na(fb_velo)] <- 0
#Creating a new varible that is the percentage of a swing and miss (dividing whiffs by swings)
#Replacing any "na" in the data with "0" 
```

```{r}
mod_velo_swing_and_miss =  lm(formula = swing_and_miss_pct ~ velocity, data = fb_velo)
#Creating a model using velocity as a predictor varibale for swing and miss percentage
```

```{r}
summary(mod_velo_swing_and_miss)
#Producing a summary of the model from above (velocity predicting swing and miss percentage)
```

```{r}
scatter.smooth(x=fb_velo$velocity, y=fb_velo$swing_and_miss_pct, main="swing_and_miss_pct ~ velocity")
#Creating a scatter plot with a line of best fit as a visual alongside the model (showing the relationship between swing and miss percentage and average fastball velocity)
```

```{r}
mod_spin_swing_and_miss =  lm(formula = swing_and_miss_pct ~ spin_rate, data = fb_velo)
#Creating a model using spin rate as a predictor varibale for swing and miss percentage
```

```{r}
summary(mod_spin_swing_and_miss)
#Producing a summary of the model from above (spin rate predicting swing and miss percentage)
```

```{r}
scatter.smooth(x=fb_velo$spin_rate, y=fb_velo$swing_and_miss_pct, main="swing_and_miss_pct ~ spin_rate")
#Creating a scatter plot with a line of best fit as a visual alongside the model (showing the relationship between swing and miss percentage and average fastball spin rate)
```

```{r}
mod_velo_spin_ba = lm(formula = ba ~ velocity + spin_rate + I(log(total_pitches)), data = fb_velo)
#Creating a model using velocity, spin rate, and total pitches as a predictor varibale for batting average
```

```{r}
summary(mod_velo_spin_ba)
termplot(mod_velo_spin_ba,partial.resid = T, se = T)
#Producing a summary of the model from above (velocity,spin rate, and total pitches predicting batting average)
#Plotting regression term agaisnt the predictors (batting average agaisnt velocity, spin rate, and total pitches)
```

```{r}
mod_velo_spin_slg = lm(formula = slg ~ velocity + spin_rate + I(log(total_pitches)), data = fb_velo)
#Creating a model using velocity, spin rate, and total pitches as a predictor varibale for sluggling percentage
```

```{r}
summary(mod_velo_spin_slg)
termplot(mod_velo_spin_slg,partial.resid = T, se = T)
#Producing a summary of the model from above (velocity,spin rate, and total pitches predicting slugging percentage)
#Plotting regression term agaisnt the predictors (slugging percentage agaisnt velocity, spin rate, and total pitches)
```



```{r}
mod_velo_spin_swing_and_miss = lm(formula = swing_and_miss_pct ~ velocity + spin_rate + I(log(total_pitches)), data = fb_velo)
#Creating a model using velocity, spin rate, and total pitches as a predictor varibale for swing and miss percentage
```

```{r}
summary(mod_velo_spin_swing_and_miss)
termplot(mod_velo_spin_swing_and_miss,partial.resid = T, se = T)
#Producing a summary of the model from above (velocity,spin rate, and total pitches predicting swing and miss percentage)
#Plotting regression term agaisnt the predictors (swing and miss percentage agaisnt velocity, spin rate, and total pitches)
```


