---
title: "How Does Velocity Affect Fastball Success?"
author: "Luke Stageberg"
date: "March 25, 2019"
output: html_document
---

```{r}

fb_velo = read.csv('./Fastball_Data.csv')
```

```{r}
hist(fb_velo$velocity, breaks = 20)
```

```{r}
mod_velo_ba = lm(formula = ba ~ velocity, data = fb_velo)
```

```{r}
summary(mod_velo_ba)
```

```{r}
scatter.smooth(x=fb_velo$velocity, y=fb_velo$ba, main="ba ~ velocity")
```

```{r}
mod_velo_slg = lm(formula = slg ~ velocity, data = fb_velo)
```

```{r}
summary(mod_velo_slg)
```

```{r}
scatter.smooth(x=fb_velo$velocity, y=fb_velo$slg, main="slg ~ velocity")
```

```{r}
mod_spin_ba = lm(formula = ba ~ spin_rate, data = fb_velo)
```

```{r}
summary(mod_spin_ba)
```

```{r}
scatter.smooth(x=fb_velo$spin_rate, y=fb_velo$ba, main="ba ~ spin_rate")
```

```{r}
mod_spin_slg = lm(formula = slg ~ spin_rate, data = fb_velo)
```

```{r}
summary(mod_spin_slg)
```

```{r}
scatter.smooth(x=fb_velo$spin_rate, y=fb_velo$slg, main="slg ~ spin_rate")
```

```{r}
fb_velo$swing_and_miss_pct = with(fb_velo, whiffs / swings)
fb_velo[is.na(fb_velo)] <- 0
```

```{r}
mod_velo_swing_and_miss =  lm(formula = swing_and_miss_pct ~ velocity, data = fb_velo)
```

```{r}
summary(mod_velo_swing_and_miss)
```

```{r}
scatter.smooth(x=fb_velo$velocity, y=fb_velo$swing_and_miss_pct, main="swing_and_miss_pct ~ velocity")
```

```{r}
mod_spin_swing_and_miss =  lm(formula = swing_and_miss_pct ~ spin_rate, data = fb_velo)
```

```{r}
summary(mod_spin_swing_and_miss)
```

```{r}
scatter.smooth(x=fb_velo$spin_rate, y=fb_velo$swing_and_miss_pct, main="swing_and_miss_pct ~ spin_rate")
```

```{r}
mod_velo_spin_ba = lm(formula = ba ~ velocity + spin_rate + I(log(total_pitches)), data = fb_velo)
```

```{r}
summary(mod_velo_spin_ba)
termplot(mod_velo_spin_ba,partial.resid = T, se = T)
```

```{r}
mod_velo_spin_slg = lm(formula = slg ~ velocity + spin_rate + I(log(total_pitches)), data = fb_velo)
```

```{r}
summary(mod_velo_spin_slg)
termplot(mod_velo_spin_slg,partial.resid = T, se = T)
```



```{r}
mod_velo_spin_swing_and_miss = lm(formula = swing_and_miss_pct ~ velocity + spin_rate + I(log(total_pitches)), data = fb_velo)
```

```{r}
summary(mod_velo_spin_swing_and_miss)
termplot(mod_velo_spin_swing_and_miss,partial.resid = T, se = T)
```


